Models/ErrorViewModel.cs
namespace Paychex_SimpleTimeClock.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TimeClockModel.cs
namespace Paychex_SimpleTimeClock.Models
{
    public class TimeClockModel
    {
        //public 
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Paychex_SimpleTimeClock.DataAccess.Interface;
using Paychex_SimpleTimeClock.DataAccess.Repository;
using Paychex_SimpleTimeClock.Models;
using System.Diagnostics;

namespace Paychex_SimpleTimeClock.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPaychexDataAccess _paychexDataAccess;

        public HomeController(IPaychexDataAccess payChexDataAccess) 
        {
            _paychexDataAccess = payChexDataAccess;
        }


        //Get 
        //public IActionResult Index([FromQuery] variableName)
        //Post
        //public IActionResult Index([FromBody] variableName)

        public IActionResult Index() => View();

        public async Task<IActionResult> AuthenticatePaychex([FromBody] List<KeyValuePair<string, object>> obj)
        {
            var userID = (await _paychexDataAccess.Login(obj.GetStringValue("Username"), obj.GetStringValue("Password")));
            HttpContext.Session.SetString("UserID", userID);
               
            return !string.IsNullOrWhiteSpace(userID)
                ? View("~/Views/TimeClock/Index.cshtml")
                : Json(false);
        }
            
        



        public IActionResult Privacy() => View();

        public IActionResult Error() => View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/TimeClockController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Paychex_SimpleTimeClock.DataAccess.Interface;

namespace Paychex_SimpleTimeClock.Controllers
{
    [Authorize]
    public class TimeClockController : Controller
    {
        private readonly IPaychexDataAccess _paychexDataAccess;
        public TimeClockController(IPaychexDataAccess paychexDataAccess)
        {
            _paychexDataAccess  = paychexDataAccess;
        }



        // GET: TimeClockController
        public async Task<IActionResult> Index()
        {
            var someValue = await _paychexDataAccess.GetAvailableBreaks();
            return View(someValue.ToList());
        } 

        // GET: TimeClockController/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}
        //
        //// GET: TimeClockController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}
        //
        //// POST: TimeClockController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
        //
        //// GET: TimeClockController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}
        //
        //// POST: TimeClockController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
        //
        //// GET: TimeClockController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}
        //
        //// POST: TimeClockController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@*src=""*@
<script type="text/javascript" asp-append-version="true">
    var paychex = paychex || {};
    $(()=>{
        var GetAuthenticationFieldsValue = () => {
            var postValue = [];
            postValue.push(

                {
                    "Key": "Username",
                    "Value": $("#txtUsername").val()
                });
            postValue.push(
                {
                    "Key": "Password",
                    "Value": $("#txtPassword").val()
                });
            return postValue;
        }

        $("#btnLogin").on("click", () => {
            paychex.ajaxCall("Home/AuthenticatePaychex", GetAuthenticationFieldsValue())
                .then((response) => {
                    Response.redirect("/TimeClock");
                    //$.magnificPopup.clse();
                    if (!JSON.parse(response))
                        paychex.openPopup('#modalEmailError');
                });
        })
    });
</script>


<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <p><input id="txtUsername" placeholder="Enter Username" /></p>
    <p><input id="txtPassword" placeholder="Enter Password" type="password" /></p>
    <p><button id="btnLogin">Login</button></p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Paychex_SimpleTimeClock</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Paychex_SimpleTimeClock.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Paychex_SimpleTimeClock</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TimeClock" asp-action="Index">Time Clock</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Paychex_SimpleTimeClock - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_SecuredLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Paychex_SimpleTimeClock - TimeClock</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Paychex_SimpleTimeClock.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Paychex_SimpleTimeClock</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TimeClock" asp-action="Index">Time Clock</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Paychex_SimpleTimeClock - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/TimeClock/Index.cshtml
@using Paychex_SimpleTimeClock.DatabaseObjects
@{
    ViewData["Title"] = "Time Clock";
    var _model = (List<AvailableBreaks>)Model;
    var s = _model;
}

<div class="text-center">
    <h1 class="display-4">Welcome to the Secured Side</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<table class="table">
    <thead>        
        <tr>
            <th scope="col">Break ID</th>
            <th scope="col">Shift ID</th>
            <th scope="col">Break Name</th>
            <th scope="col">Active</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row"></th>
            <td>v.AvailableShiftID</td>
            <td>v.AvailableBreakName</td>
            <td>v.Active</td>
        </tr>
@foreach(var v in Model)
{
        <tr>
            <th scope="row">@v.AvailableBreakID</th>
            <td>@v.AvailableShiftID</td>
            <td>
                <input name="AvailableBreakName" type="text" value="@v.AvailableBreakName" />
            </td>
                <td>
                    <input type=checkbox name="Active" checked="@v.Active" value="true" class="form-check-input" />
                </td>
        </tr>
 }
    </tbody>
</table>